### PR TITLE
add astronomer suggestions

### PR DESCRIPTION
**Pull request by thomasdziedzic-census**
## Description of the change

wisott

## How tested

`poetry run pytest` passes

## Security implications

none

### CODE REVIEW

**Review by sutrolabs-githubapprover — APPROVED** [review]
Automatically approving minor fix.

**Review by sutrolabs-githubapprover — APPROVED** [review]
Automatically approving minor fix.

**Comment by pgzmnk** [comment]
I would keep the restructuring of the example DAG to be consistent with conventions. This aims to promote readability and surface the key `census_conn_id` parameter.

See: https://github.com/pgzmnk/airflow-provider-census/blob/master/airflow_provider_census/example_dags/example_census.py

**Comment by thomasdziedzic-census** [comment]
Added the example DAG changes.

**Review by pgzmnk — APPROVED** [review]

**Pull request merged**
